/**
 * see https://api.flutter.dev/flutter/animation/Curves-class.html
 */
export enum Curves {
    linear = 'linear',
    fastEaseInToSlowEaseOut = 'fastEaseInToSlowEaseOut',
    bounceIn = 'bounceIn',
    bounceInOut = 'bounceInOut',
    bounceOut = 'bounceOut',
    decelerate = 'decelerate',
    ease = 'ease',
    easeIn = 'easeIn',
    easeInBack = 'easeInBack',
    easeInCirc = 'easeInCirc',
    easeInSine = 'easeInSine',
    easeInCubic = 'easeInCubic',
    easeInExpo = 'easeInExpo',
    easeInOutCubicEmphasized = 'easeInOutCubicEmphasized',
    easeInOutBack = 'easeInOutBack',
    easeInOutCirc = 'easeInOutCirc',
    easeInOutExpo = 'easeInOutExpo',
    easeInOutQuad = 'easeInOutQuad',
    easeInOutQuart = 'easeInOutQuart',
    easeInOutQuint = 'easeInOutQuint',
    easeInOutSine = 'easeInOutSine',
    easeInToLinear = 'easeInToLinear',
    easeOutSine = 'easeOutSine',
    easeOutBack = 'easeOutBack',
    easeOutCirc = 'easeOutCirc',
    easeOutCubic = 'easeOutCubic',
    easeOutExpo = 'easeOutExpo',
    easeOutQuad = 'easeOutQuad',
    easeOutQuart = 'easeOutQuart',
    easeOutQuint = 'easeOutQuint',
    linearToEaseOut = 'linearToEaseOut',
    slowMiddle = 'slowMiddle',
    fastOutSlowIn = 'fastOutSlowIn',
    elasticIn = 'elasticIn',
    elasticInOut = 'elasticInOut',
    elasticOut = 'elasticOut'
  }