export enum FloatingActionButtonLocation {
    centerDocked = 0,
    centerFloat,
    centerTop,
    endDocked,
    endFloat,
    endTop,
    startDocked,
    startFloat,
    startTop,
    miniCenterDocked,
    miniCenterFloat,
    miniCenterTop,
    miniEndDocked,
    miniEndFloat,
    miniEndTop,
    miniStartDocked,
    miniStartFloat,
    miniStartTop,
}